name: BePilot API - CI/CD Pipeline


on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Compilar projeto e executar Testes Unitários
        run: mvn clean verify

      - name: Relatório de Build
        run: echo "Build finalizado! Integração do Spring Data JPA e testes validados com sucesso."